# Site settings
title: Matthias Diener
email: mdiener@illinois.edu
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://matthiasdiener.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  matthiasdiener

# Build settings
markdown: kramdown

analytics:
  provider: google
  google:
    tracking_id: 'UA-40553066-1'
